sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t adamgillies/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true adamgillies/docker-react npm run test